### PR TITLE
Cmake improvements

### PR DESCRIPTION
**Pull request by sum01**
What this PR does:

- Fixes the minimum Cmake version, because `cxx_std_17` was already in use.
- Optional use of system libraries instead of (mostly) git submodule libs.
- Improves flexibility of installation dirs by using [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html?highlight=gnuinstalldirs)
- Speeds up recompilation by not rebuilding unchanged files.
- Fine-tunes the compiler options/definitions
- Allows for `find_package(Acid)` to work on systems that already have Acid installed. This will import an `Acid::Acid` target for linking.
- Add [CTest](https://cmake.org/cmake/help/latest/module/CTest.html?highlight=ctest) support for automatically running the tests, and add an option `ACID_INSTALL_EXAMPLES` to not install said tests.

It does a little more, but I tried to write meaningful commit messages for that reason :)

I would love some notes on if I missed anything, or accidentally mangled previously working features. Hopefully that didn't happen, but I might have missed something.

---

~TODO: Use `CTest` to automatically test the tests, and add an option to not install said tests.~

### CODE REVIEW

**Comment by mattparks** [comment]
Appveyor would have probably built fine, OpenAL SDK has been a big issue. However on Unix systems bullet libraries cannot have the location property read? I have no idea why this might be happening.

**Comment by sum01** [comment]
I (tried) to take the libraries properties and put them into variables with the same names as from the FindXXX modules, but it didn't work.

I'm not sure of the fix just yet, but what I was attempting was to not having to change what you `target_link_libraries(Acid)` regarless of it was system or submodule libs.

**Comment by sum01** [comment]
So I think I fixed nearly everything, although I can't run the tests without changing their include paths. They all include the subdirs of Acid without an `Acid` prefix, like `<Inputs/Mouse.hpp>` instead of `<Acid/Inputs/Mouse.hpp>`

I know how to make that work from a minor cmake change, although I'm not sure if it's current behaviour is desired.

**Comment by mattparks** [comment]
It's probably not a bad idea to require includes to Acid to be prefixed by `Acid/` in tests and projects using Acid.

**Comment by mattparks** [comment]
I have spent some time testing out your most recent changes, they appear to be working correctly so I will be merging into master. If you have any other future fixes please feel free to open a pull request, thank you so much for rewriting Acids CMake files.

**Pull request merged**
